name: pro_health
description: A new Flutter application.

version: 2.5.37+6

environment:
  sdk: ">=2.2.2 <11.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  flutter_screenutil: ^5.0.0
  smooth_star_rating: ^1.1.1
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.0
  convex_bottom_bar: ^3.0.0
  icon_badge: ^1.0.0
  otp_screen: ^0.0.3
  expansion_tile_card: ^2.0.0
  select_form_field: ^2.0.0
  flutter_datetime_picker: ^1.2.5
  custom_dropdown: ^0.0.2
  datetime_picker_formfield: ^2.0.0
  dropdown_search: ^0.5.0
  searchable_dropdown: ^1.1.0
  http: ^0.13.1
  rxdart: ^0.26.0
  dio: ^4.0.0
  find_dropdown: ^1.0.0
  grouped_buttons: ^1.0.4
  fdottedline: ^1.0.1
  html_editor: ^1.0.1
  simple_autocomplete_formfield: ^0.3.0
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.4.0
  auto_animated: ^3.0.0
  flare_flutter: ^3.0.0
  flutter_staggered_animations: ^1.0.0
  page_transition: ^1.1.5
  cached_network_image: ^3.0.0
  flutter_spinkit: ^5.0.0
  rflutter_alert: ^2.0.2
  weekday_selector: ^1.0.0
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^2.0.1
  path: ^1.7.0
  pdf: ^3.2.0
  flutter_html_to_pdf: ^0.6.0
  flutter_switch: ^0.3.1
  page_indicator: ^0.4.1
  marquee: ^2.1.0
  percent_indicator: ^3.0.1
  oktoast: ^3.0.0
  splashscreen: ^1.3.5
  multi_image_picker: ^4.7.15
  image_picker: ^0.6.4
  group_radio_button: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icons/doctor/
    - assets/icons/patient/
  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoeuil.ttf
          weight: 500
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_launcher_name:
  name: "ProHealth"