name: pro_health
description: A new Flutter application.

version: 2.4.37+6

environment:
  sdk: ">=2.2.2 <11.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  font_awesome_flutter: ^8.11.0
  flutter_screenutil: ^0.4.2
  smooth_star_rating: ^1.1.1
  intl: ^0.16.0
  flutter_launcher_icons: ^0.7.3
  flutter_launcher_name: ^0.0.1
  convex_bottom_bar: ^2.6.0
  icon_badge: ^0.0.1+5
  otp_screen: ^0.0.3
  expansion_tile_card: ^1.1.0
  select_form_field: ^1.0.0
  flutter_datetime_picker: ^1.2.5
  custom_dropdown: ^0.0.2
  datetime_picker_formfield: ^1.0.0
  dropdown_search: ^0.4.8
  searchable_dropdown: ^1.1.0
  http: ^0.12.1
  rxdart: ^0.23.1
  dio: ^3.0.1
  find_dropdown: ^0.2.2
  grouped_buttons: ^1.0.4
  fdottedline: ^1.0.1
  html_editor: ^1.0.1
  simple_autocomplete_formfield: ^0.2.7
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.3.3
  responsive_widgets: ^0.1.10
  auto_animated: ^1.2.3
  flare_flutter: ^1.8.0
  flutter_staggered_animations: ^0.1.2
  page_transition: ^1.1.5
  cached_network_image: ^2.2.0+1
  flutter_spinkit: ^4.1.2
  rflutter_alert: ^1.1.0
  weekday_selector: ^0.4.0
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.6.27
  path: ^1.7.0
  pdf: ^1.5.0
  flutter_html_to_pdf: ^0.5.2
  flutter_switch: ^0.2.0
  page_indicator: ^0.3.0
  marquee: ^1.7.0
  percent_indicator: ^3.0.1
  oktoast: ^3.0.0
  splashscreen: ^1.3.5
  multi_image_picker: ^4.7.15
  image_picker: ^0.6.6+1
  group_radio_button: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icons/doctor/
    - assets/icons/doctor/cexchange.png
    - assets/icons/doctor/covid19.png
    - assets/icons/patient/
  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoeuil.ttf
          weight: 500
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_launcher_name:
  name: "ProHealth"